export const SAVE_CATS = 'SAVE_CATS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SAVE_CAT_SELECTED = 'SAVE_CAT_SELECTED';
export const SAVE_ORIGINS_TO_SHOW = 'SAVE_ORIGINS_TO_SHOW';
export const SAVE_ORIGINS = 'SAVE_ORIGINS';
